/**
 * Weekly deal catalogue seed — itemized hot deals per store and promotion tier.
 * Sourced from live Coles, Woolworths, and ALDI catalogue screenshots (Jun 2026).
 * Consumed by buildDealsForCycle() on first seed, grocery refresh, and tasks/seedWeeklyDeals.js.
 */

/** @typedef {import('./weeklyDeals.js').WeeklyDealDoc} WeeklyDealDoc */

/**
 * @type {Array<Partial<WeeklyDealDoc> & { name: string; store: string; dealPrice: number }>}
 */
export const WEEKLY_DEAL_TEMPLATES = [
  // —— Coles (Screenshot 2026-06-07 at 7.17.45 PM) ——
  {
    name: 'Cadbury Dairy Milk Block Chocolate 160g-190g',
    store: 'coles',
    dealPrice: 4.0,
    originalPrice: 8.0,
    dealType: 'Half Price',
    savingsText: 'Half Price!',
    category: 'Pantry',
  },
  {
    name: 'Sanitarium Up&Go Liquid Breakfast 3x250mL',
    store: 'coles',
    dealPrice: 3.5,
    originalPrice: 7.0,
    dealType: 'Half Price',
    savingsText: 'Half Price!',
    category: 'Pantry',
  },
  {
    name: "Smith's Crinkle Cut Potato Chips 150g-170g",
    store: 'coles',
    dealPrice: 2.5,
    originalPrice: 5.0,
    dealType: 'Half Price',
    savingsText: 'Half Price!',
    category: 'Pantry',
  },
  {
    name: 'Continental Cup a Soup 2 Serves 50g-75g',
    store: 'coles',
    dealPrice: 1.4,
    originalPrice: 2.8,
    dealType: 'Half Price',
    savingsText: 'Half Price!',
    category: 'Pantry',
  },
  {
    name: 'Finish Dishwashing Tablets 56pk',
    store: 'coles',
    dealPrice: 18.0,
    originalPrice: 36.0,
    dealType: 'Half Price',
    savingsText: 'Half Price!',
    category: 'Household',
  },

  // —— Woolworths (Screenshots 2026-06-07 at 7.18.36 PM & 7.19.58 PM) ——
  {
    name: 'Oreo Cookies 136g-140g',
    store: 'woolworths',
    dealPrice: 1.6,
    originalPrice: 3.2,
    dealType: 'Half Price',
    savingsText: 'Half Price!',
    category: 'Pantry',
  },
  {
    name: 'Pringles Potato Chips 118g-134g',
    store: 'woolworths',
    dealPrice: 2.75,
    originalPrice: 5.5,
    dealType: 'Half Price',
    savingsText: 'Half Price!',
    category: 'Pantry',
  },
  {
    name: "Maltesers or M&M's 120g-180g",
    store: 'woolworths',
    dealPrice: 3.5,
    originalPrice: 7.0,
    dealType: 'Half Price',
    savingsText: 'Half Price!',
    category: 'Pantry',
  },
  {
    name: 'Coca-Cola Classic, Diet or Zero Sugar 24 x 375ml',
    store: 'woolworths',
    dealPrice: 24.0,
    originalPrice: 37.5,
    dealType: 'Super Saver',
    savingsText: 'Save $13.50',
    category: 'Pantry',
  },
  {
    name: 'Primo Kransky Double Smoked or Cheese',
    store: 'woolworths',
    dealPrice: 11.25,
    originalPrice: 22.5,
    dealType: 'Half Price',
    savingsText: 'Half Price!',
    category: 'Fresh',
  },
  {
    name: "D'Orsogna Chicken Sandwich Schnitzel",
    store: 'woolworths',
    dealPrice: 1.4,
    originalPrice: 2.8,
    dealType: 'Half Price',
    savingsText: 'Half Price!',
    category: 'Fresh',
  },
  {
    name: 'Huggies Bulk Nappies',
    store: 'woolworths',
    dealPrice: 28.0,
    originalPrice: 42.0,
    dealType: 'Super Saver',
    savingsText: 'Save $14.00',
    category: 'Baby',
  },

  // —— ALDI (Screenshot 2026-06-07 at 7.21.56 PM) ——
  {
    name: 'Ready, Set...Cook! Sweet & Sour Pork Meal Kit 800g',
    store: 'aldi',
    dealPrice: 14.99,
    originalPrice: null,
    dealType: 'Price Drop',
    savingsText: 'Price Drop',
    category: 'Fresh',
  },
  {
    name: 'The Fishmonger Salmon Fish Cakes 2pk/290g',
    store: 'aldi',
    dealPrice: 5.99,
    originalPrice: null,
    dealType: 'Price Drop',
    savingsText: 'Price Drop',
    category: 'Fresh',
  },
  {
    name: 'Australian Afourer Mandarins 750g Pack',
    store: 'aldi',
    dealPrice: 2.99,
    originalPrice: null,
    dealType: 'Price Drop',
    savingsText: 'Price Drop',
    category: 'Fresh',
  },
  {
    name: 'Barossa Fine Foods Salami 200g',
    store: 'aldi',
    dealPrice: 3.49,
    originalPrice: null,
    dealType: 'Price Drop',
    savingsText: 'Price Drop',
    category: 'Fresh',
  },

  // —— Harris Farm ——
  {
    name: 'Imperfect Picks Seasonal Fruit 1kg',
    store: 'harrisfarm',
    dealPrice: 3.99,
    originalPrice: 6.99,
    dealType: 'Price Drop',
    savingsText: 'Price Drop',
    category: 'Fresh',
  },
  {
    name: 'Harris Farm Greek Yoghurt 1kg',
    store: 'harrisfarm',
    dealPrice: 5.5,
    originalPrice: 8.99,
    dealType: 'Super Saver',
    savingsText: 'Super Saver',
    category: 'Dairy',
  },
  {
    name: 'Grass-Fed Beef Mince 500g',
    store: 'harrisfarm',
    dealPrice: 9.99,
    originalPrice: 14.99,
    dealType: 'Price Drop',
    savingsText: 'Price Drop',
    category: 'Fresh',
  },
  {
    name: 'Harris Farm Sourdough Loaf',
    store: 'harrisfarm',
    dealPrice: 4.5,
    originalPrice: 6.5,
    dealType: 'Half Price',
    savingsText: 'Half Price!',
    category: 'Bakery',
  },

  // —— Costco ——
  {
    name: 'Kirkland Signature Mixed Nuts 1.13kg',
    store: 'costco',
    dealPrice: 18.99,
    originalPrice: 24.99,
    dealType: 'Super Saver',
    savingsText: 'Warehouse Value',
    category: 'Pantry',
  },
  {
    name: 'Kirkland Signature Paper Towels 12pk',
    store: 'costco',
    dealPrice: 22.99,
    originalPrice: 29.99,
    dealType: 'Super Saver',
    savingsText: 'Bulk Buy Value',
    category: 'Household',
  },
  {
    name: 'Australian Lamb Leg Roast per kg',
    store: 'costco',
    dealPrice: 14.99,
    originalPrice: 19.99,
    dealType: 'Price Drop',
    savingsText: 'Price Drop',
    category: 'Fresh',
  },
  {
    name: 'Kirkland Signature Liquid Laundry Detergent 5.99L',
    store: 'costco',
    dealPrice: 19.99,
    originalPrice: 26.99,
    dealType: 'Super Saver',
    savingsText: 'Warehouse Value',
    category: 'Household',
  },
];
