/** @typedef {{ id: string, title: string, prepTime: string, cookTime?: string, ingredients: string[], instructions: string[], cuisine?: string, mainIngredient?: string, source?: string, sourceUrl?: string, imageUrl?: string, category?: string, calories?: number, macros?: { protein?: string, carbs?: string, fat?: string, calories?: number }, missingIngredients?: string[], isAiGenerated?: boolean, matchingInventoryCount?: number, expiringItemsUsed?: string[] }} Recipe */

export const BUILTIN_RECIPES = [
  {
    id: 'creamy-basil-chicken',
    title: 'Creamy Basil Chicken',
    prepTime: '35 min',
    ingredients: [
      'Chicken Thighs',
      'Basil',
      'Thick Cream',
      'Garlic',
      'Onions',
      'Olive Oil',
    ],
    instructions: [
      'Season chicken thighs with salt and pepper. Sear in olive oil until golden, then set aside.',
      'Sauté diced onion and minced garlic until soft. Pour in thick cream and simmer 3–4 minutes.',
      'Return chicken to the pan, tear in fresh basil, and simmer until cooked through.',
      'Taste and adjust seasoning. Serve hot with rice or crusty bread.',
    ],
  },
  {
    id: 'chorizo-carbonara',
    title: 'Chorizo Carbonara Pasta',
    prepTime: '25 min',
    ingredients: ['Chorizo', 'Pasta', 'Eggs', 'Parmesan', 'Garlic', 'Black Pepper'],
    instructions: [
      'Cook pasta in salted boiling water until al dente. Reserve 1 cup pasta water.',
      'Brown sliced chorizo in a pan. Add minced garlic for 30 seconds.',
      'Whisk eggs, grated Parmesan, and plenty of black pepper in a bowl.',
      'Toss drained pasta with chorizo off the heat, then quickly mix in the egg mixture.',
      'Loosen with pasta water until silky. Serve immediately with extra Parmesan.',
    ],
  },
  {
    id: 'spicy-stir-fry',
    title: 'Spicy Veggie Stir-Fry',
    prepTime: '20 min',
    ingredients: [
      'Bell Peppers',
      'Broccoli',
      'Soy Sauce',
      'Ginger',
      'Garlic',
      'Rice',
      'Chili Flakes',
    ],
    instructions: [
      'Cook rice according to package directions.',
      'Stir-fry broccoli and sliced bell peppers in hot oil over high heat for 4–5 minutes.',
      'Add minced garlic, ginger, soy sauce, and chili flakes. Toss 1 minute more.',
      'Serve over rice and finish with sesame oil if you have it.',
    ],
  },
  {
    id: 'greek-chicken-bowl',
    title: 'Greek Chicken Power Bowl',
    prepTime: '30 min',
    ingredients: [
      'Chicken Breast',
      'Cucumber',
      'Tomatoes',
      'Feta Cheese',
      'Olives',
      'Lemon',
      'Olive Oil',
    ],
    instructions: [
      'Grill or pan-sear seasoned chicken breast until cooked through. Rest and slice.',
      'Chop cucumber and tomatoes. Combine with olives and crumbled feta.',
      'Whisk lemon juice, olive oil, salt, and pepper for a quick dressing.',
      'Layer chicken over salad, drizzle dressing, and serve.',
    ],
  },
  {
    id: 'beef-tacos',
    title: 'Weeknight Beef Tacos',
    prepTime: '22 min',
    ingredients: [
      'Beef Mince',
      'Taco Shells',
      'Lettuce',
      'Tomatoes',
      'Cheddar Cheese',
      'Sour Cream',
      'Onions',
    ],
    instructions: [
      'Brown ground beef with diced onion. Season with salt, pepper, and taco spices.',
      'Warm taco shells in the oven or skillet.',
      'Chop lettuce and tomatoes. Shred cheddar.',
      'Fill shells with beef and toppings. Finish with sour cream.',
    ],
  },
  {
    id: 'salmon-lemon-dill',
    title: 'Lemon Dill Salmon',
    prepTime: '28 min',
    ingredients: ['Salmon Fillet', 'Lemon', 'Dill', 'Butter', 'Asparagus', 'Garlic'],
    instructions: [
      'Pat salmon dry. Season with salt, pepper, lemon zest, and chopped dill.',
      'Pan-sear or bake at 200°C / 400°F for 12–15 minutes until flaky.',
      'Sauté asparagus with garlic in butter until tender-crisp.',
      'Serve salmon over asparagus with lemon wedges and melted butter.',
    ],
  },
  {
    id: 'egg-fried-rice',
    title: 'High-Protein Egg Fried Rice',
    prepTime: '18 min',
    ingredients: ['Eggs', 'Rice', 'Soy Sauce', 'Frozen Peas', 'Carrots', 'Sesame Oil', 'Spring Onions'],
    instructions: [
      'Use day-old rice if possible. Scramble eggs in a hot wok, then set aside.',
      'Stir-fry diced carrots and peas until bright. Add rice and break up clumps.',
      'Return eggs, splash in soy sauce, and toss on high heat.',
      'Finish with sesame oil and sliced green onion.',
    ],
  },
  {
    id: 'thai-holy-basil-chicken',
    title: 'Thai Holy Basil Chicken (Pad Krapow)',
    prepTime: '22 min',
    cuisine: 'Asian',
    ingredients: [
      'Chicken Thighs',
      'Basil',
      'Garlic',
      'Rice',
      'Soy Sauce',
      'Chili Flakes',
      'Onions',
    ],
    instructions: [
      'Cook jasmine or plain rice. Finely chop garlic and slice onion.',
      'Mince or pound chicken thighs. Stir-fry garlic and onion in hot oil until fragrant.',
      'Add chicken and cook through on high heat. Splash in soy sauce and chili flakes.',
      'Tear in plenty of basil, toss 30 seconds, and serve over rice with a fried egg if you like.',
    ],
  },
  {
    id: 'teriyaki-chicken-bowl',
    title: 'Teriyaki Chicken Rice Bowl',
    prepTime: '28 min',
    cuisine: 'Asian',
    ingredients: [
      'Chicken Breast',
      'Rice',
      'Soy Sauce',
      'Ginger',
      'Garlic',
      'Sesame Oil',
      'Spring Onions',
    ],
    instructions: [
      'Cook rice. Mix soy sauce, grated ginger, minced garlic, and a little honey or sugar for teriyaki glaze.',
      'Pan-sear sliced chicken breast until golden. Brush with glaze and cook until sticky.',
      'Steam or stir-fry broccoli or carrots on the side if you have them.',
      'Serve chicken over rice, drizzle remaining glaze, and finish with sesame oil and green onion.',
    ],
  },
  {
    id: 'korean-bibimbap-bowl',
    title: 'Korean Bibimbap-Style Bowl',
    prepTime: '30 min',
    cuisine: 'Asian',
    ingredients: [
      'Rice',
      'Eggs',
      'Beef Mince',
      'Soy Sauce',
      'Garlic',
      'Carrots',
      'Spinach',
      'Sesame Oil',
      'Chili Flakes',
    ],
    instructions: [
      'Cook rice. Season beef mince with soy sauce, garlic, and sesame oil; cook in a hot pan until browned.',
      'Quickly sauté julienned carrots and spinach (or any veg) with a pinch of salt.',
      'Fry eggs sunny-side up. Arrange rice in bowls with veg and beef around the edges.',
      'Top with egg, chili flakes, and extra sesame oil. Mix everything together before eating.',
    ],
  },
  {
    id: 'vietnamese-lemon-chicken',
    title: 'Vietnamese-Style Lemon Chicken',
    prepTime: '25 min',
    cuisine: 'Asian',
    ingredients: [
      'Chicken Thighs',
      'Lemon',
      'Garlic',
      'Ginger',
      'Soy Sauce',
      'Rice',
      'Fish Sauce',
      'Spring Onions',
    ],
    instructions: [
      'Marinate chicken thighs 15 minutes in lemon juice, fish sauce (or extra soy), garlic, and ginger.',
      'Grill or pan-sear chicken until charred at the edges and cooked through. Rest and slice.',
      'Cook rice. Warm any leftover marinade in the pan as a light sauce.',
      'Serve chicken over rice with lemon wedges, sliced green onion, and herbs if you have them.',
    ],
  },
  {
    id: 'japanese-miso-salmon',
    title: 'Miso-Ginger Glazed Salmon',
    prepTime: '24 min',
    cuisine: 'Asian',
    ingredients: [
      'Salmon Fillet',
      'Miso Paste',
      'Ginger',
      'Soy Sauce',
      'Rice',
      'Garlic',
      'Sesame Oil',
    ],
    instructions: [
      'Whisk miso paste, grated ginger, soy sauce, and a little water into a smooth glaze.',
      'Brush salmon fillets with glaze. Bake at 200°C / 400°F for 12–14 minutes or pan-sear skin-side down first.',
      'Cook rice. Sauté garlic in sesame oil and toss with steamed greens if available.',
      'Serve salmon over rice with extra glaze spooned on top.',
    ],
  },
  {
    id: 'nepali-chicken-curry',
    title: 'Nepali Chicken Curry (Kukhura ko Tarkari)',
    prepTime: '40 min',
    cuisine: 'Nepali',
    ingredients: [
      'Chicken Thighs',
      'Onions',
      'Garlic',
      'Ginger',
      'Tomatoes',
      'Turmeric',
      'Cumin',
      'Rice',
      'Coriander',
    ],
    instructions: [
      'Blend or finely chop onion, garlic, ginger, and tomatoes into a rough paste (or chop small).',
      'Brown chicken pieces in oil. Add turmeric and cumin; stir until fragrant.',
      'Pour in the paste and simmer 20–25 minutes, adding a splash of water if it sticks.',
      'Season with salt. Serve with steamed rice and fresh cilantro.',
    ],
  },
  {
    id: 'dal-bhat',
    title: 'Dal Bhat (Lentil & Rice Plate)',
    prepTime: '35 min',
    cuisine: 'Nepali',
    ingredients: [
      'Red Lentils',
      'Rice',
      'Onions',
      'Garlic',
      'Ginger',
      'Turmeric',
      'Cumin',
      'Tomatoes',
      'Ghee',
    ],
    instructions: [
      'Rinse lentils. Simmer with turmeric, chopped garlic, ginger, and water until soft (25–30 min).',
      'In a small pan, fry cumin seeds in ghee (or oil) with diced onion until golden; stir into dal.',
      'Cook rice separately. Dice tomatoes and stir into dal for the last 5 minutes.',
      'Serve dal over rice — the classic Nepali comfort meal. Pickles or salad on the side if you have them.',
    ],
  },
  {
    id: 'nepali-potato-curry',
    title: 'Nepali Potato Curry (Aloo Tarkari)',
    prepTime: '30 min',
    cuisine: 'Nepali',
    ingredients: [
      'Potatoes',
      'Onions',
      'Garlic',
      'Ginger',
      'Tomatoes',
      'Turmeric',
      'Cumin',
      'Coriander',
      'Rice',
    ],
    instructions: [
      'Peel and cube potatoes. Par-boil 8 minutes until just tender; drain.',
      'Sauté onion, garlic, and ginger in oil. Add turmeric and cumin, then diced tomatoes.',
      'Add potatoes and a little water. Simmer until saucy and potatoes are fully tender.',
      'Garnish with cilantro and serve with rice or roti.',
    ],
  },
  {
    id: 'nepali-momo-soup',
    title: 'Nepali Momo Jhol (Dumpling Soup)',
    prepTime: '45 min',
    cuisine: 'Nepali',
    ingredients: [
      'Chicken Mince',
      'Wonton Wrappers',
      'Onions',
      'Garlic',
      'Ginger',
      'Tomatoes',
      'Soy Sauce',
      'Coriander',
      'Chili Flakes',
    ],
    instructions: [
      'Mix chicken mince with finely chopped onion, garlic, ginger, soy sauce, and cilantro for filling.',
      'Spoon filling onto wonton wrappers, pleat, and seal. Steam dumplings 10–12 minutes until cooked.',
      'For jhol: blend tomatoes, ginger, garlic, and chili with water; simmer 10 minutes. Season with soy and lemon.',
      'Pour warm jhol over steamed momos. Top with cilantro and serve immediately.',
    ],
  },
  {
    id: 'thukpa-noodle-soup',
    title: 'Thukpa (Nepali Noodle Soup)',
    prepTime: '35 min',
    cuisine: 'Nepali',
    ingredients: [
      'Egg Noodles',
      'Chicken Thighs',
      'Onions',
      'Garlic',
      'Ginger',
      'Tomatoes',
      'Soy Sauce',
      'Spinach',
      'Coriander',
    ],
    instructions: [
      'Simmer sliced chicken in water with onion, garlic, and ginger for a simple broth (20 min).',
      'Shred chicken back into the pot. Add diced tomatoes and soy sauce; simmer 5 minutes more.',
      'Cook egg noodles separately. Divide noodles into bowls and ladle hot broth over.',
      'Top with spinach (wilts in the bowl) and cilantro. Adjust salt and chili to taste.',
    ],
  },
  {
    id: 'lemon-butter-barramundi',
    title: 'Lemon Butter Barramundi',
    prepTime: '22 min',
    cuisine: 'Australian',
    mainIngredient: 'Barramundi Fillet',
    ingredients: [
      'Barramundi Fillet',
      'Lemon',
      'Butter',
      'Garlic',
      'Parsley',
      'Asparagus',
      'Olive Oil',
    ],
    instructions: [
      'Pat barramundi dry and season with salt and pepper.',
      'Pan-sear fillets in olive oil 3–4 minutes per side until golden and cooked through.',
      'Melt butter with minced garlic and lemon juice; spoon over fish.',
      'Serve with steamed asparagus and chopped parsley.',
    ],
  },
  {
    id: 'lamb-roast-dinner',
    title: 'Roast Lamb with Vegetables',
    prepTime: '75 min',
    cuisine: 'Australian',
    mainIngredient: 'Lamb Leg',
    ingredients: [
      'Lamb Leg',
      'Potatoes',
      'Carrots',
      'Dried Rosemary',
      'Garlic',
      'Olive Oil',
      'Onions',
    ],
    instructions: [
      'Rub lamb with olive oil, garlic, rosemary, salt, and pepper.',
      'Roast at 180°C / 350°F with halved potatoes and carrots for about 1 hour 15 minutes.',
      'Rest lamb 10 minutes before carving.',
      'Serve with pan juices and roasted vegetables.',
    ],
  },
  {
    id: 'beef-stir-fry-broccoli',
    title: 'Beef & Broccoli Stir-Fry',
    prepTime: '20 min',
    cuisine: 'Asian',
    mainIngredient: 'Beef Mince',
    ingredients: [
      'Beef Mince',
      'Broccoli',
      'Soy Sauce',
      'Garlic',
      'Ginger',
      'Rice',
      'Sesame Oil',
    ],
    instructions: [
      'Cook rice. Stir-fry beef mince in hot oil until browned; set aside.',
      'Stir-fry broccoli with garlic and ginger until bright green.',
      'Return beef, add soy sauce and a splash of water; toss 1 minute.',
      'Serve over rice with sesame oil.',
    ],
  },
  {
    id: 'scotch-fillet-steak',
    title: 'Pan-Seared Scotch Fillet',
    prepTime: '25 min',
    mainIngredient: 'Scotch Fillet',
    ingredients: [
      'Scotch Fillet',
      'Butter',
      'Garlic',
      'Dried Rosemary',
      'Potatoes',
      'Green Beans',
    ],
    instructions: [
      'Bring steaks to room temperature. Season generously.',
      'Sear in a hot pan 3–4 minutes per side for medium-rare.',
      'Baste with butter, garlic, and rosemary in the last minute.',
      'Rest 5 minutes. Serve with potatoes and green beans.',
    ],
  },
  {
    id: 'pumpkin-soup',
    title: 'Creamy Pumpkin Soup',
    prepTime: '35 min',
    ingredients: [
      'Pumpkin',
      'Onions',
      'Garlic',
      'Vegetable Stock',
      'Thick Cream',
      'Olive Oil',
      'Bread',
    ],
    instructions: [
      'Sauté diced onion and garlic in olive oil until soft.',
      'Add cubed pumpkin and stock. Simmer 20 minutes until tender.',
      'Blend until smooth. Stir in cream and season.',
      'Serve with crusty bread.',
    ],
  },
  {
    id: 'mushroom-risotto',
    title: 'Mushroom Risotto',
    prepTime: '40 min',
    cuisine: 'Italian',
    ingredients: [
      'Mushrooms',
      'Rice',
      'Onions',
      'Garlic',
      'Parmesan',
      'Vegetable Stock',
      'Butter',
      'Olive Oil',
    ],
    instructions: [
      'Sauté sliced mushrooms in butter until golden; set aside.',
      'Cook diced onion in olive oil, add rice and toast 1 minute.',
      'Add warm stock one ladle at a time, stirring until creamy (25–30 min).',
      'Fold in mushrooms and Parmesan. Serve immediately.',
    ],
  },
  {
    id: 'berry-yogurt-parfait',
    title: 'Berry Yogurt Parfait',
    prepTime: '10 min',
    ingredients: [
      'Mixed Berries',
      'Greek Yogurt',
      'Honey',
      'Granola',
      'Mint',
    ],
    instructions: [
      'Layer Greek yogurt, mixed berries, and granola in glasses.',
      'Drizzle with honey between layers.',
      'Top with fresh mint and serve chilled.',
    ],
  },
  {
    id: 'chicken-veggie-tray-bake',
    title: 'Chicken & Vegetable Tray Bake',
    prepTime: '45 min',
    mainIngredient: 'Chicken Thighs',
    ingredients: [
      'Chicken Thighs',
      'Potatoes',
      'Carrots',
      'Zucchini',
      'Olive Oil',
      'Garlic',
      'Mixed Herbs',
    ],
    instructions: [
      'Toss chopped vegetables with olive oil, garlic, and herbs on a baking tray.',
      'Nestle seasoned chicken thighs among the vegetables.',
      'Roast at 200°C / 400°F for 35–40 minutes until chicken is cooked through.',
      'Rest 5 minutes before serving.',
    ],
  },
  {
    id: 'prawn-garlic-pasta',
    title: 'Garlic Prawn Pasta',
    prepTime: '25 min',
    mainIngredient: 'Prawns',
    ingredients: [
      'Prawns',
      'Pasta',
      'Garlic',
      'Butter',
      'Lemon',
      'Parsley',
      'Chili Flakes',
      'Olive Oil',
    ],
    instructions: [
      'Cook pasta until al dente. Reserve pasta water.',
      'Sauté prawns in olive oil and butter with garlic and chili until pink.',
      'Toss pasta with prawns, lemon juice, parsley, and pasta water.',
      'Serve immediately with extra lemon.',
    ],
  },
  {
    id: 'celery-apple-salad',
    title: 'Crunchy Celery & Apple Salad',
    prepTime: '12 min',
    ingredients: [
      'Celery',
      'Apples',
      'Lemon',
      'Olive Oil',
      'Greek Yogurt',
      'Walnuts',
    ],
    instructions: [
      'Thinly slice celery and apple. Toss with lemon juice to prevent browning.',
      'Whisk yogurt, olive oil, salt, and pepper for dressing.',
      'Combine salad with dressing and toasted walnuts.',
      'Serve chilled as a side.',
    ],
  },
];
