import {
  BABY_CATEGORY,
  FOOD_CATEGORY,
  HOUSEHOLD_CATEGORY,
  ITEM_TYPE,
} from './constants.js';

/**
 * Household & grocery product knowledge for typeahead suggestions.
 * Optional `aliases` improve matching for AU spellings, brands, and shorthand.
 *
 * @typedef {{ name: string, itemType: 'Food'|'Household'|'Baby', category: string, aliases?: string[] }} ProductCatalogEntry
 */

/** @type {ProductCatalogEntry[]} */
export const PRODUCT_CATALOG = [
  // ── Household — Cleaning ─────────────────────────────────────
  { name: 'Dishwashing Liquid', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Dishwashing Tablets', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Multi-Surface Spray', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Sponges', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Paper Towels', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Garbage Bags', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Glass Cleaner', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Dishcloths', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Floor Cleaner', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Disinfectant Wipes', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Multi-Purpose Wipes', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Microfiber Cloths', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Bleach', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Window Cleaner', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Drain Cleaner', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Rubber Gloves', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Aluminium Foil', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Baking Paper', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  {
    name: 'Toilet Cleaner',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.CLEANING,
    aliases: ['toilet bowl cleaner', 'bathroom cleaner', 'toilet gel', 'harpic', 'white king toilet'],
  },
  {
    name: 'Toilet Bowl Cleaner',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.CLEANING,
    aliases: ['toilet blocks', 'toilet duck', 'loo cleaner'],
  },
  {
    name: 'Bathroom Cleaner',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.CLEANING,
    aliases: ['shower cleaner', 'mould remover', 'mold remover', 'bathroom spray'],
  },
  {
    name: 'Oven Cleaner',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.CLEANING,
    aliases: ['bbq cleaner', 'grill cleaner'],
  },
  {
    name: 'Antibacterial Spray',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.CLEANING,
    aliases: ['detol spray', 'dettol surface'],
  },
  // ── Household — Laundry ──────────────────────────────────────
  { name: 'Laundry Powder', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Laundry Liquid', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Fabric Softener', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Stain Remover', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Dryer Sheets', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Washing Pegs', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Laundry Pods', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Fabric Stain Remover Spray', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Lint Roller', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  // ── Household — Bathroom ─────────────────────────────────────
  { name: 'Toilet Paper', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Hand Soap', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Shampoo', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Conditioner', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Body Wash', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Toothpaste', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Deodorant', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Face Masks', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Moisturiser', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Razors', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  // ── Food — Ambient ───────────────────────────────────────────
  { name: 'Pasta', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Rice', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Bread', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Olive Oil', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Vegetable Oil', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Soy Sauce', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Tomato Sauce', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Pasta Sauce', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Flour', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Sugar', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Honey', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Oats', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Cereal', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Baked Beans', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Tuna', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Biscuits', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Salt', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Sea Salt', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Black Pepper', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Ground Pepper', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Paprika', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Cumin', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Turmeric', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Oregano', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Cinnamon', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Chili Powder', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Chili Flakes', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Garlic Powder', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Onion Powder', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Curry Powder', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Mixed Herbs', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Italian Herbs', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Stock Cubes', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Baking Powder', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Sriracha', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Maple Syrup', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Peanut Butter', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Rolled Oats', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'White Vinegar', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Apple Cider Vinegar', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Panko Breadcrumbs', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Canned Chickpeas', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Canned Black Beans', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Coconut Milk', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Tuna Cans', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Chicken Stock', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Vegetable Stock', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  {
    name: 'Potato Chips',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['chips', 'crisps', 'kettle chips', 'smittys chips', 'smiths chips', 'red rock deli'],
  },
  {
    name: 'Corn Chips',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['nacho chips', 'doritos', 'corn chips'],
  },
  {
    name: 'Tortilla Chips',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['nachos'],
  },
  {
    name: 'Popcorn',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['microwave popcorn', 'poppin'],
  },
  {
    name: 'Rice Crackers',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['sakata', 'peckish'],
  },
  {
    name: 'Muesli Bars',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['carmans', 'uncle tobys bars'],
  },
  // ── Food — Fresh — Dairy & yogurt ──────────────────────────────
  { name: 'Milk', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Eggs', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Butter', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Greek Yogurt',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['greek yoghurt', 'chobani', 'farmers union greek'],
  },
  {
    name: 'Natural Yogurt',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['natural yoghurt', 'plain yogurt', 'plain yoghurt'],
  },
  {
    name: 'Vanilla Yogurt',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['vanilla yoghurt', 'yogurt vanilla'],
  },
  {
    name: 'Strawberry Yogurt',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['strawberry yoghurt', 'berry yogurt'],
  },
  {
    name: 'Yogurt Pouches',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['yoghurt pouches', 'kids yogurt', 'squeezie yogurt', 'tam tam valley pouches', 'yoplait pouches'],
  },
  {
    name: 'Drinking Yogurt',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['yogurt drink', 'yakult', 'farmers union drinking yoghurt'],
  },
  {
    name: 'Cottage Cheese',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['cottage', 'low fat cottage cheese', 'bulla cottage'],
  },
  { name: 'Cheddar Cheese', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Parmesan', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Mozzarella', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Sour Cream', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Cream Cheese', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Feta Cheese',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['feta'],
  },
  {
    name: 'Ricotta',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['ricotta cheese'],
  },
  {
    name: 'Thick Cream',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['thickened cream', 'pouring cream', 'whipping cream'],
  },
  // ── Food — Fresh — Meat ────────────────────────────────────────
  { name: 'Chicken Thighs', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Chicken Breast', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Beef Mince', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Lamb Chops',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['lamb cutlets', 'lamb loin chops'],
  },
  {
    name: 'Lamb Leg',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['leg of lamb', 'roast lamb'],
  },
  {
    name: 'Lamb Mince',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['minced lamb', 'lamb mince'],
  },
  {
    name: 'Lamb Shoulder',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['lamb roast', 'shoulder of lamb'],
  },
  {
    name: 'Rack of Lamb',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['lamb rack'],
  },
  { name: 'Pork Chops', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Pork Belly',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['belly pork', 'roast pork belly'],
  },
  {
    name: 'Pork Mince',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['minced pork'],
  },
  {
    name: 'Pork Sausages',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pork snags', 'thick pork sausages'],
  },
  {
    name: 'Pork Tenderloin',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pork fillet'],
  },
  {
    name: 'Pork Roast',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pork shoulder roast', 'leg pork roast'],
  },
  {
    name: 'Bacon',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['streaky bacon', 'short cut bacon'],
  },
  { name: 'Chorizo', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Beef Steak',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['scotch fillet', 'sirloin', 'rump steak', 'porterhouse'],
  },
  // ── Food — Fresh — Seafood ───────────────────────────────────
  { name: 'Salmon Fillet', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Barramundi Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['barramundi', 'barra', 'baramundi', 'barramundi fish'],
  },
  {
    name: 'Snapper Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['snapper', 'red snapper'],
  },
  {
    name: 'Flathead Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['flathead', 'flat head'],
  },
  {
    name: 'Prawns',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['king prawns', 'tiger prawns', 'green prawns', 'shrimp'],
  },
  {
    name: 'Calamari',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['squid', 'salt and pepper squid'],
  },
  {
    name: 'Tuna Steak',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['yellowfin tuna', 'fresh tuna'],
  },
  {
    name: 'Fish Fillets',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['white fish', 'fish fillet'],
  },
  // ── Food — Fresh — Fruit ─────────────────────────────────────
  { name: 'Apples', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Bananas', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Oranges',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['orange', 'navel oranges', 'valencia oranges'],
  },
  {
    name: 'Mandarins',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['mandarin', 'easy peel mandarins', 'imperial mandarins', 'clementines'],
  },
  {
    name: 'Blood Oranges',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['blood orange'],
  },
  {
    name: 'Grapefruit',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['ruby grapefruit', 'pink grapefruit'],
  },
  { name: 'Lemons', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Limes', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Berries',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['strawberries', 'blueberries', 'raspberries'],
  },
  {
    name: 'Grapes',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['green grapes', 'red grapes'],
  },
  {
    name: 'Watermelon',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['rockmelon', 'cantaloupe', 'honeydew'],
  },
  { name: 'Avocados', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  // ── Food — Fresh — Vegetables ────────────────────────────────
  { name: 'Tomatoes', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Lettuce', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Bell Peppers', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Broccoli', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Spinach', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Carrots', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Cucumbers', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Mushrooms', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Ginger', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Basil', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Potatoes',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['potato', 'brushed potatoes', 'washed potatoes', 'royal blue potatoes', 'kipfler'],
  },
  {
    name: 'Sweet Potato',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['kumara', 'sweet potatoes'],
  },
  {
    name: 'Onions',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['brown onion', 'red onion'],
  },
  {
    name: 'Garlic',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['garlic bulb'],
  },
  {
    name: 'Zucchini',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['courgette'],
  },
  {
    name: 'Capsicum',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['red capsicum', 'green capsicum'],
  },
  {
    name: 'Corn Cobs',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['corn', 'sweet corn'],
  },
  {
    name: 'Spring Onions',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['shallots', 'green onions'],
  },
  // ── Food — Freezer ───────────────────────────────────────────
  { name: 'Frozen Peas', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FREEZER },
  { name: 'Frozen Berries', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FREEZER },
  { name: 'Ice Cream', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FREEZER },
  { name: 'Frozen Pizza', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FREEZER },
  {
    name: 'Frozen Chips',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['oven chips', 'frozen french fries', 'potato gems', 'wedges frozen'],
  },
  {
    name: 'Frozen Fish Fillets',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen barramundi', 'frozen fish'],
  },
  // ── Baby ─────────────────────────────────────────────────────
  { name: 'Nappies Size 1', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.DIAPERS },
  { name: 'Nappies Size 2', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.DIAPERS },
  { name: 'Nappies Size 3', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.DIAPERS },
  { name: 'Nappies Size 4', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.DIAPERS },
  { name: 'Nappies Size 5', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.DIAPERS },
  { name: 'Baby Formula', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.FOOD },
  { name: 'Baby Puree Pouches', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.FOOD },
  { name: 'Baby Rusks', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.FOOD },
  { name: 'Infant Cereal', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.FOOD },
  { name: 'Baby Lotion', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Nappy Rash Cream', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Baby Powder', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Biodegradable Baby Wipes', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Baby Body Wash', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Baby Shampoo', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Teething Gel', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Dummy / Pacifier', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Baby Sunscreen', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
];
