import {
  BABY_CATEGORY,
  FOOD_CATEGORY,
  HOUSEHOLD_CATEGORY,
  ITEM_TYPE,
} from './constants.js';
import { withAustralianStoreAliases } from './auStoreProductAliases.js';

/**
 * Household & grocery product knowledge for typeahead suggestions.
 * Optional `aliases` improve matching for AU spellings, brands, and shorthand.
 *
 * @typedef {{ name: string, itemType: 'Food'|'Household'|'Baby', category: string, aliases?: string[] }} ProductCatalogEntry
 */

/** @type {ProductCatalogEntry[]} */
const BASE_PRODUCT_CATALOG = [
  // ── Household — Cleaning ─────────────────────────────────────
  { name: 'Dishwashing Liquid', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Dishwashing Tablets', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Multi-Surface Spray', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Sponges', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Paper Towels', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Garbage Bags', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Glass Cleaner', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Dishcloths', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Floor Cleaner', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Disinfectant Wipes', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Multi-Purpose Wipes', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Microfiber Cloths', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Bleach', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Window Cleaner', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Drain Cleaner', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Rubber Gloves', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Aluminium Foil', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  { name: 'Baking Paper', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.CLEANING },
  {
    name: 'Toilet Cleaner',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.CLEANING,
    aliases: ['toilet bowl cleaner', 'bathroom cleaner', 'toilet gel', 'harpic', 'white king toilet'],
  },
  {
    name: 'Toilet Bowl Cleaner',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.CLEANING,
    aliases: ['toilet blocks', 'toilet duck', 'loo cleaner'],
  },
  {
    name: 'Bathroom Cleaner',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.CLEANING,
    aliases: ['shower cleaner', 'mould remover', 'mold remover', 'bathroom spray'],
  },
  {
    name: 'Oven Cleaner',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.CLEANING,
    aliases: ['bbq cleaner', 'grill cleaner'],
  },
  {
    name: 'Antibacterial Spray',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.CLEANING,
    aliases: ['detol spray', 'dettol surface'],
  },
  // ── Household — Laundry ──────────────────────────────────────
  { name: 'Laundry Powder', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Laundry Liquid', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Fabric Softener', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Stain Remover', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Dryer Sheets', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Washing Pegs', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Laundry Pods', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Fabric Stain Remover Spray', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  { name: 'Lint Roller', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.LAUNDRY },
  // ── Household — Bathroom ─────────────────────────────────────
  { name: 'Toilet Paper', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Hand Soap', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Shampoo', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Conditioner', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Body Wash', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Toothpaste', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Deodorant', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Face Masks', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Moisturiser', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  { name: 'Razors', itemType: ITEM_TYPE.HOUSEHOLD, category: HOUSEHOLD_CATEGORY.BATHROOM },
  {
    name: 'Sanitary Pads',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.BATHROOM,
    aliases: ['pads', 'period pads', 'menstrual pads', 'sanitary napkins', 'libra', 'always pads', 'u by kotex pads'],
  },
  {
    name: 'Panty Liners',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.BATHROOM,
    aliases: ['liners', 'panty liner', 'daily liners', 'carefree liners', 'libra liners'],
  },
  {
    name: 'Tampons',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.BATHROOM,
    aliases: ['tampon', 'tampax', 'u by kotex tampons', 'libra tampons'],
  },
  {
    name: 'Menstrual Cup',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.BATHROOM,
    aliases: ['period cup', 'diva cup', 'lunette', 'moon cup'],
  },
  {
    name: 'Period Underwear',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.BATHROOM,
    aliases: ['modibodi', 'period undies', 'menstrual underwear', 'bonds bloody comfy'],
  },
  {
    name: 'Maternity Pads',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.BATHROOM,
    aliases: ['postpartum pads', 'maternity liners', 'mum pads'],
  },
  {
    name: 'Incontinence Pads',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.BATHROOM,
    aliases: ['adult pads', 'continence pads', 'poise', 'depend pads', 'tena pads'],
  },
  {
    name: 'Sanitary Bags',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.BATHROOM,
    aliases: ['period disposal bags', 'hygiene bags', 'sanitary disposal'],
  },
  {
    name: 'Feminine Wipes',
    itemType: ITEM_TYPE.HOUSEHOLD,
    category: HOUSEHOLD_CATEGORY.BATHROOM,
    aliases: ['intimate wipes', 'feminine hygiene wipes', 'vagisil wipes'],
  },
  // ── Food — Ambient ───────────────────────────────────────────
  { name: 'Pasta', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Rice', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Bread', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Olive Oil', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Vegetable Oil', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Soy Sauce', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Tomato Sauce', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Pasta Sauce', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Flour', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Sugar', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Honey', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Oats', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Cereal', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Baked Beans', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Tuna', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Biscuits', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Salt', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Sea Salt', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Black Pepper', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Ground Pepper', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Paprika', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Cumin', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Turmeric', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Oregano', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Cinnamon', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Chili Powder', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Chili Flakes', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Garlic Powder', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Onion Powder', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Curry Powder', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Mixed Herbs', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Italian Herbs', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Stock Cubes', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Baking Powder', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Sriracha', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Maple Syrup', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Peanut Butter', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Rolled Oats', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'White Vinegar', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Apple Cider Vinegar', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Panko Breadcrumbs', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Canned Chickpeas', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Canned Black Beans', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Coconut Milk', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Tuna Cans', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Chicken Stock', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  { name: 'Vegetable Stock', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.AMBIENT },
  {
    name: 'Potato Chips',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['chips', 'crisps', 'kettle chips', 'smittys chips', 'smiths chips', 'red rock deli'],
  },
  {
    name: 'Corn Chips',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['nacho chips', 'doritos', 'corn chips'],
  },
  {
    name: 'Tortilla Chips',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['nachos'],
  },
  {
    name: 'Popcorn',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['microwave popcorn', 'poppin'],
  },
  {
    name: 'Rice Crackers',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['sakata', 'peckish'],
  },
  {
    name: 'Muesli Bars',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.AMBIENT,
    aliases: ['carmans', 'uncle tobys bars'],
  },
  // ── Food — Fresh — Dairy & yogurt ──────────────────────────────
  { name: 'Milk', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Eggs', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Butter', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Greek Yogurt',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['greek yoghurt', 'chobani', 'farmers union greek'],
  },
  {
    name: 'Natural Yogurt',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['natural yoghurt', 'plain yogurt', 'plain yoghurt'],
  },
  {
    name: 'Vanilla Yogurt',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['vanilla yoghurt', 'yogurt vanilla'],
  },
  {
    name: 'Strawberry Yogurt',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['strawberry yoghurt', 'berry yogurt'],
  },
  {
    name: 'Yogurt Pouches',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['yoghurt pouches', 'kids yogurt', 'squeezie yogurt', 'tam tam valley pouches', 'yoplait pouches'],
  },
  {
    name: 'Drinking Yogurt',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['yogurt drink', 'yakult', 'farmers union drinking yoghurt'],
  },
  {
    name: 'Cottage Cheese',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['cottage', 'low fat cottage cheese', 'bulla cottage'],
  },
  { name: 'Cheddar Cheese', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Parmesan', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Mozzarella', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Sour Cream', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Cream Cheese', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Feta Cheese',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['feta'],
  },
  {
    name: 'Ricotta',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['ricotta cheese'],
  },
  {
    name: 'Thick Cream',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['thickened cream', 'pouring cream', 'whipping cream'],
  },
  // ── Food — Fresh — Meat ────────────────────────────────────────
  { name: 'Chicken Thighs', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Chicken Breast', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Beef Mince', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Scotch Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['scotch fillet steak', 'rib eye', 'ribeye'],
  },
  {
    name: 'Sirloin Steak',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['sirloin', 'new york strip'],
  },
  {
    name: 'Rump Steak',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['rump', 'rump cap'],
  },
  {
    name: 'Porterhouse Steak',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['porterhouse', 't bone', 't-bone steak'],
  },
  {
    name: 'Eye Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['fillet steak', 'tenderloin', 'beef tenderloin'],
  },
  {
    name: 'Chuck Steak',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['chuck', 'gravy beef'],
  },
  {
    name: 'Blade Steak',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['oyster blade', 'flat iron steak'],
  },
  {
    name: 'Beef Ribs',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['short ribs', 'beef short ribs', 'bbq ribs'],
  },
  {
    name: 'Beef Brisket',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['brisket', 'corned beef brisket'],
  },
  {
    name: 'Beef Sausages',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['beef snags', 'thick beef sausages'],
  },
  {
    name: 'Beef Stir Fry Strips',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['beef strips', 'stir fry beef'],
  },
  {
    name: 'Beef Steak',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['steak'],
  },
  {
    name: 'Lamb Chops',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['lamb cutlets', 'lamb loin chops'],
  },
  {
    name: 'Lamb Leg',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['leg of lamb', 'roast lamb'],
  },
  {
    name: 'Lamb Mince',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['minced lamb', 'lamb mince'],
  },
  {
    name: 'Lamb Shoulder',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['lamb roast', 'shoulder of lamb'],
  },
  {
    name: 'Rack of Lamb',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['lamb rack'],
  },
  { name: 'Pork Chops', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Pork Belly',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['belly pork', 'roast pork belly'],
  },
  {
    name: 'Pork Mince',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['minced pork'],
  },
  {
    name: 'Pork Sausages',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pork snags', 'thick pork sausages'],
  },
  {
    name: 'Pork Tenderloin',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pork fillet'],
  },
  {
    name: 'Pork Roast',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pork shoulder roast', 'leg pork roast'],
  },
  {
    name: 'Bacon',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['streaky bacon', 'short cut bacon'],
  },
  { name: 'Chorizo', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  // ── Food — Fresh — Seafood ───────────────────────────────────
  {
    name: 'Salmon Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['atlantic salmon', 'sockeye salmon', 'salmon portion'],
  },
  {
    name: 'Barramundi Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['barramundi', 'barra', 'baramundi', 'barramundi fish', 'australian barramundi'],
  },
  {
    name: 'Snapper Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['snapper', 'red snapper', 'crimson snapper'],
  },
  {
    name: 'Flathead Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['flathead', 'flat head', 'southern flathead'],
  },
  {
    name: 'Prawns',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['king prawns', 'tiger prawns', 'green prawns', 'shrimp', 'school prawns'],
  },
  {
    name: 'King Prawns',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['jumbo prawns', 'large prawns'],
  },
  {
    name: 'Tiger Prawns',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['black tiger prawns'],
  },
  {
    name: 'Banana Prawns',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['banana prawn'],
  },
  {
    name: 'Cooked Prawns',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['peeled prawns cooked', 'ready to eat prawns'],
  },
  {
    name: 'Calamari',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['squid', 'salt and pepper squid', 'squid tubes'],
  },
  {
    name: 'Tuna Steak',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['yellowfin tuna', 'fresh tuna', 'ahi tuna'],
  },
  {
    name: 'Fish Fillets',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['white fish', 'fish fillet', 'boneless fish fillets'],
  },
  {
    name: 'Ocean Trout Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['ocean trout', 'tasmanian trout', 'steelhead trout'],
  },
  {
    name: 'Rainbow Trout Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['rainbow trout', 'trout fillet'],
  },
  {
    name: 'Whiting Fillets',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['whiting', 'sand whiting', 'school whiting'],
  },
  {
    name: 'Hoki Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['hoki', 'new zealand hoki'],
  },
  {
    name: 'Blue Grenadier Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['grenadier', 'deep sea dory', 'blue grenadier'],
  },
  {
    name: 'Cod Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['cod', 'pacific cod'],
  },
  {
    name: 'Kingfish Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['yellowtail kingfish', 'kingfish', 'hiramasa'],
  },
  {
    name: 'Trevally Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['trevally', 'silver trevally'],
  },
  {
    name: 'Mahi Mahi Fillet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['mahi mahi', 'dolphinfish'],
  },
  {
    name: 'Swordfish Steak',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['swordfish', 'broadbill'],
  },
  {
    name: 'Smoked Salmon',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['hot smoked salmon', 'cold smoked salmon', 'smoked salmon slices'],
  },
  {
    name: 'Mussels',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['green lip mussels', 'black mussels', 'mussel pot'],
  },
  {
    name: 'Oysters',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['sydney rock oysters', 'pacific oysters', 'dozen oysters'],
  },
  {
    name: 'Scallops',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['sea scallops', 'roeless scallops'],
  },
  {
    name: 'Octopus',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['baby octopus', 'octopus tentacles'],
  },
  {
    name: 'Blue Swimmer Crab',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['swimmer crab', 'sand crab', 'blue crab'],
  },
  {
    name: 'Mud Crab',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['mangrove crab', 'queensland mud crab'],
  },
  {
    name: 'Moreton Bay Bugs',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['bay bugs', 'moreton bay bug', 'balmain bugs'],
  },
  {
    name: 'Rock Lobster',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['crayfish', 'southern rock lobster', 'wa crayfish'],
  },
  {
    name: 'Sardines',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['fresh sardines', 'pilchards'],
  },
  {
    name: 'Whole Barramundi',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['whole barra', 'barramundi whole'],
  },
  // ── Food — Fresh — Fruit ─────────────────────────────────────
  { name: 'Apples', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Bananas', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Oranges',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['orange', 'navel oranges', 'valencia oranges'],
  },
  {
    name: 'Mandarins',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['mandarin', 'easy peel mandarins', 'imperial mandarins', 'clementines'],
  },
  {
    name: 'Blood Oranges',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['blood orange'],
  },
  {
    name: 'Grapefruit',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['ruby grapefruit', 'pink grapefruit'],
  },
  { name: 'Lemons', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Limes', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Strawberries',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['strawberry', 'strawbs'],
  },
  {
    name: 'Blueberries',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['blueberry'],
  },
  {
    name: 'Raspberries',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['raspberry'],
  },
  {
    name: 'Blackberries',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['blackberry'],
  },
  {
    name: 'Mixed Berries',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['berries', 'berry mix', 'berry medley'],
  },
  {
    name: 'Cranberries',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['cranberry', 'fresh cranberries'],
  },
  {
    name: 'Pears',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pear', 'packham pear', 'williams pear'],
  },
  {
    name: 'Peaches',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['peach', 'white peach'],
  },
  {
    name: 'Nectarines',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['nectarine'],
  },
  {
    name: 'Plums',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['plum', 'black plums'],
  },
  {
    name: 'Apricots',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['apricot'],
  },
  {
    name: 'Cherries',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['cherry'],
  },
  {
    name: 'Kiwi Fruit',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['kiwi', 'kiwifruit'],
  },
  {
    name: 'Pineapple',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pineapples'],
  },
  {
    name: 'Mango',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['mangoes', 'mangos', 'kent mango'],
  },
  {
    name: 'Papaya',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pawpaw', 'papaw'],
  },
  {
    name: 'Passionfruit',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['passion fruit', 'pulp passionfruit'],
  },
  {
    name: 'Pomegranate',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pomegranates'],
  },
  {
    name: 'Figs',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['fig'],
  },
  {
    name: 'Grapes',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['green grapes', 'red grapes'],
  },
  {
    name: 'Watermelon',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['rockmelon', 'cantaloupe', 'honeydew'],
  },
  { name: 'Avocados', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Pink Lady Apples',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pink lady', 'gala apples', 'granny smith', 'jazz apples'],
  },
  // ── Food — Fresh — Vegetables ────────────────────────────────
  { name: 'Tomatoes', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Lettuce', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Bell Peppers', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Broccoli', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Spinach', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Baby Spinach',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['baby spinach leaves'],
  },
  {
    name: 'Kale',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['tuscan kale', 'curly kale'],
  },
  { name: 'Carrots', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Cucumbers', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Celery',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['celery bunch', 'celery sticks'],
  },
  { name: 'Mushrooms', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Cauliflower',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['cauliflower head'],
  },
  {
    name: 'Cabbage',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['green cabbage', 'red cabbage', 'wombok', 'chinese cabbage'],
  },
  {
    name: 'Bok Choy',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['pak choy', 'buk choy', 'asian greens'],
  },
  {
    name: 'Silverbeet',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['chard', 'rainbow chard'],
  },
  {
    name: 'Eggplant',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['aubergine'],
  },
  {
    name: 'Asparagus',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['asparagus bunch'],
  },
  {
    name: 'Green Beans',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['beans', 'string beans'],
  },
  {
    name: 'Snow Peas',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['sugar snap peas', 'snap peas'],
  },
  {
    name: 'Pumpkin',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['butternut pumpkin', 'kent pumpkin', 'jap pumpkin'],
  },
  {
    name: 'Leeks',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['leek'],
  },
  {
    name: 'Beetroot',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['beets', 'fresh beetroot'],
  },
  {
    name: 'Parsnip',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['parsnips'],
  },
  {
    name: 'Brussels Sprouts',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['brussel sprouts'],
  },
  {
    name: 'Cos Lettuce',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['romaine', 'cos'],
  },
  {
    name: 'Iceberg Lettuce',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['iceberg'],
  },
  {
    name: 'Rocket',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['arugula', 'baby rocket'],
  },
  {
    name: 'Coriander',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['cilantro', 'fresh coriander'],
  },
  {
    name: 'Parsley',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['flat leaf parsley', 'curly parsley'],
  },
  {
    name: 'Mint',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['fresh mint'],
  },
  { name: 'Ginger', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  { name: 'Basil', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FRESH },
  {
    name: 'Potatoes',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['potato', 'brushed potatoes', 'washed potatoes', 'royal blue potatoes', 'kipfler'],
  },
  {
    name: 'Sweet Potato',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['kumara', 'sweet potatoes'],
  },
  {
    name: 'Onions',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['brown onion', 'red onion'],
  },
  {
    name: 'Garlic',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['garlic bulb'],
  },
  {
    name: 'Zucchini',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['courgette'],
  },
  {
    name: 'Capsicum',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['red capsicum', 'green capsicum'],
  },
  {
    name: 'Corn Cobs',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['corn', 'sweet corn'],
  },
  {
    name: 'Spring Onions',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FRESH,
    aliases: ['shallots', 'green onions'],
  },
  // ── Food — Freezer ───────────────────────────────────────────
  { name: 'Frozen Peas', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FREEZER },
  { name: 'Frozen Berries', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FREEZER },
  { name: 'Ice Cream', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FREEZER },
  { name: 'Frozen Pizza', itemType: ITEM_TYPE.FOOD, category: FOOD_CATEGORY.FREEZER },
  {
    name: 'Frozen Chips',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['oven chips', 'frozen french fries', 'potato gems', 'wedges frozen'],
  },
  {
    name: 'Frozen Fish Fillets',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen barramundi', 'frozen fish', 'frozen white fish'],
  },
  {
    name: 'Frozen Salmon Portions',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen salmon fillets', 'frozen salmon portions'],
  },
  {
    name: 'Frozen Barramundi Portions',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen barra portions', 'frozen barramundi fillets'],
  },
  {
    name: 'Frozen Prawns',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen raw prawns', 'frozen cooked prawns', 'frozen peeled prawns'],
  },
  {
    name: 'Frozen Calamari Rings',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen squid rings', 'frozen calamari', 'frozen salt and pepper squid'],
  },
  {
    name: 'Frozen Hoki Fillets',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen hoki', 'frozen grenadier fillets'],
  },
  {
    name: 'Frozen Fish Fingers',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['fish fingers', 'frozen fish sticks'],
  },
  {
    name: 'Frozen Crumbed Fish',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen battered fish', 'crumbed fish portions'],
  },
  {
    name: 'Frozen Seafood Mix',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen marinara mix', 'seafood medley frozen', 'frozen mussels prawns mix'],
  },
  {
    name: 'Frozen Scallops',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen roeless scallops'],
  },
  {
    name: 'Frozen Mussels',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen green lip mussels', 'frozen mussel meat'],
  },
  {
    name: 'Frozen Squid Tubes',
    itemType: ITEM_TYPE.FOOD,
    category: FOOD_CATEGORY.FREEZER,
    aliases: ['frozen squid tubes', 'frozen whole squid'],
  },
  // ── Baby ─────────────────────────────────────────────────────
  { name: 'Nappies Size 1', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.DIAPERS },
  { name: 'Nappies Size 2', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.DIAPERS },
  { name: 'Nappies Size 3', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.DIAPERS },
  { name: 'Nappies Size 4', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.DIAPERS },
  { name: 'Nappies Size 5', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.DIAPERS },
  { name: 'Baby Formula', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.FOOD },
  { name: 'Baby Puree Pouches', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.FOOD },
  { name: 'Baby Rusks', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.FOOD },
  { name: 'Infant Cereal', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.FOOD },
  { name: 'Baby Lotion', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Nappy Rash Cream', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Baby Powder', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Biodegradable Baby Wipes', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Baby Body Wash', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Baby Shampoo', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Teething Gel', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Dummy / Pacifier', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
  { name: 'Baby Sunscreen', itemType: ITEM_TYPE.BABY, category: BABY_CATEGORY.ESSENTIALS },
];

/** Curated catalogue with AU retail search aliases (see auStoreProductAliases.js). */
export const PRODUCT_CATALOG = withAustralianStoreAliases(BASE_PRODUCT_CATALOG);
